---
all:
  children:
    hypervisors:
      hosts:
        hv01.42crunch.com:
        hv02.42crunch.com:
        hv03.42crunch.com:
    dockerboxes:
      hosts:
        dockerbox01.intranet.42crunch.com:
    webservers:
      hosts:
        webserver01.intranet.42crunch.com:
    routers:
      # OpenBSD, see roles/router — hosts TBD
      hosts: {}
    monitoring:
      hosts:
        monitoring.intranet.42crunch.com:
