admin_password_hashes:
    #ENC[AES256_GCM,data:WQlOInL607U9j+NSGMj9SS2XVj85weEwChPs+8s/VZa2Lnay7mojl8jD1keDZIUmfpWaduQ9aLs9Gfm5qOFL+oOujGlD76UYlDYuUEVOLt+EsJXC2RQFDfSQ1o3in6rVbyRixxP1jgTcURheztk9qw==,iv:OkUjD+F1JEJ9jWHNRu5PZ4dbL9P0Q4hfKGTfYGdpEkQ=,tag:TSQQ2nn6USEOkUR4/iThQg==,type:comment]
    jp: ENC[AES256_GCM,data:PKydMjuBidGJdnnM1qC49dMBVSZg38SPEhOfCxCTQJzwRKIjVeLPVx+wXumKWIXRCm1Mh4MvEE1Ib94L0C6l5ZUJrtfIAHKvfTRCI0lkaqsEDj4Lb0/oinAGaYKs5EWXvwL+aiJ2FVnr3A==,iv:RMWDQoKzGgmzTysMzV0TiTy/XyDy7lnIFSy5OZJdvGA=,tag:Vy2T/u249uWv0/sjeMBJRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBemZrL3JMRnl2WDFOaytU
            TXZUbnZDQ2h3ekFKMk9pc2V3alFyUU5URkI0CmgvUHp5RWlQaVZGRTRyWTJ3d2w1
            bWlYanVrZStWVGUxZGtyQkY3NWk0ZEkKLS0tIFZXT09XSU9vRGNFZ1RNSk15YU1S
            RFJnRG16ZE5uWUk3TzVjTWpwZlVXL00KD0oVlVh61u/L2Z+yTwRvx5znZPvGfj29
            IiXBNVVLCJq361spRl6eU6UDVDhHN6EP54z0/ykW9eSICHJRu/6cHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qz3q8fgmmp7wypvfhxd8enfuuu9g24evdzwn8vpe5d4tej7y2elqx9v44p
    lastmodified: "2026-09-11T13:35:43Z"
    mac: ENC[AES256_GCM,data:v3c5whyCWFSFxd3g8KZ8bL3xiutq0aH99pPMGLhRjL3cTYIUVrWvzqnr0qmjUnu1Q1R9fx2rbYmDzQEepPwjPGJG2PgCaZZflSiNB56u9tEZRNCapIDo+F4+rIPqdLArq92ZJmKcrVAkpTHLrJc7QptLkovsvX1qJHRgvBBAsw0=,iv:36d+/hqeIccyQZru6/NqowAI82FCg2PvllW08XVPV+M=,tag:s/3Uu830e7oIgY/DVCccpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
