---
- name: Add Elastic APT repository
  ansible.builtin.deb822_repository:
    name: "elastic-{{ elastic_stack_version }}"
    types: deb
    uris: "https://artifacts.elastic.co/packages/{{ elastic_stack_version }}/apt"
    suites: stable
    components: main
    signed_by: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    install_python_debian: true

- name: Install kibana
  ansible.builtin.apt:
    name: kibana
    state: present
    update_cache: true

- name: Configure kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: "0640"
  notify: Restart kibana

- name: Ensure kibana is running and enabled
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: true
